name: Build packages for Windows

on:
  release:
    types:
      - published

jobs:
  build_windows_packages:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: git submodule update --init --recursive

      - name: Configure
        run: cmake -B build

      - name: Build
        run: cmake --build build --config Release --target install 

      - name: Package
        if: github.event_name == 'release'
        run: |
          $pkg_name="nanomq-${{ github.event.release.tag_name }}-windows-x86_64.zip"
          Compress-Archive -Path install/* -DestinationPath $pkg_name
          mv $pkg_name ./install/ 

      - uses: actions/upload-artifact@v3
        if: github.event_name == 'release'
        with:
          name: packages
          path: "install/*.zip"

      - uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ github.token }}
          file: install/nanomq*.zip
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
